language: python
python:
  - "3.6"
# command to install dependencies
install:
  - python3 setup.py install
  - pip install codecov
# command to run tests
script:
  - python3 tests/plantserver_tests.py
  - coverage run tests/plantserver_tests.py

after_success:
    codecov
